stages:
  - test
  - build
  - deploy

test:
  image: golang:1.14
  stage: test
  script:
    - go test ./...
    - go vet ./...

build:
  image: golang:1.14
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/podcastination-server
  artifacts:
    paths:
      - podcastination-server

deploy:
  stage: deploy
  script:
    - echo "Hello World!"