stages:
  - test
  - build
  - deploy

test:
  image: golang:1.14
  stage: test
  script:
    - go test ./...
    - go vet ./...

build:
  image: golang:1.14
  stage: build
  script:
    - go build -o ./bin/podcastination-server ./cmd/podcastination-server
  artifacts:
    paths:
      - bin/

deploy:
  stage: deploy
  script:
    - echo "Hello World!"