stages:
  - test
  - release
  - build
  - deploy

test:
  image: golang:1.14
  stage: test
  allow_failure: false
  script:
    - go test ./...
    - go vet ./...
  only:
    - master
    - develop
  tags:
    - docker

release:
  stage: release
  image: node:13
  needs:
    - job: test
  allow_failure: false
  before_script:
    - npm install @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
  script:
    - npx semantic-release
  tags:
    - docker
  only:
    - master

build:
  image: golang:1.14
  stage: build
  allow_failure: false
  needs:
    - release
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/podcastination-server
  artifacts:
    paths:
      - podcastination-server
    expire_in: 7 days
  only:
    - master
  tags:
    - docker

deploy:
  stage: deploy
  image: alpine
  needs:
    - job: build
      artifacts: true
  allow_failure: false
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 44' --progress --delete podcastination-server gitlab@lu-church.de:/opt/podcastination-server/bin
    - ssh gitlab@lu-church.de -p 44 "sudo systemctl restart podcastination-server.service"
  tags:
    - docker
  only:
    - master
