name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v -o ./podcastination-server

      - name: Test
        run: go test -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: ./podcastination-server
          # The desired behavior if no files are found using the provided path.

  deploy:
    if: contains( github.ref, 'master' )
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10

      - name: Run a multi-line script
        run: |
          ls -a
          echo Add other actions to build,
          echo test, and deploy your project.
