name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v -o ./podcastination-server

      - name: Test
        run: go test -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: podcastination-server
          # A file, directory or wildcard pattern that describes what to upload
          path: ./podcastination-server
          # The desired behavior if no files are found using the provided path.

  release:
    needs:
      - build
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/github
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: podcastination-server

      - name: Run a multi-line script
        run: |
          echo Going to release...
          apt add --no-cache rsync openssh
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          rsync -rav -e 'ssh -p 44' --progress --delete podcastination-server gitlab@lu-church.de:/opt/podcastination-server/bin
          ssh gitlab@lu-church.de -p 44 "sudo systemctl restart podcastination-server.service"

          echo Done :)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PROD_D_SERVER }}
