name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v -o ./podcastination-server

      - name: Test
        run: go test -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: podcastination-server
          # A file, directory or wildcard pattern that describes what to upload
          path: ./podcastination-server
          # The desired behavior if no files are found using the provided path.

  release:
    needs:
      - build
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/github
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: podcastination-server

      - name: rsync deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -rav --progress --delete --chmod=Du=rwx,Dg=rx,D=,Fu=rw,Fg=rx,Fo= --recursive
          path: podcastination-server
          remote_path: /opt/podcastination-server/bin
          remote_host: lu-church.de
          remote_port: 44
          remote_user: gitlab
          remote_key: ${{ secrets.SSH_PROD_D_SERVER }}

      - name: restart service
        uses: appleboy/ssh-action@master
        with:
          host: lu-church.de
          username: gitlab
          key: ${{ secrets.SSH_PROD_D_SERVER }}
          port: 44
          script: sudo systemctl restart podcastination-server.service